### ISSUE TITLE
Upload file error:  <html> <head><title>413 Request Entity 

### ISSUE THREAD

**Issue by veritasnondatur** [loosolab/wilson#1]
Dear developers,
I have been trying to use the web instance of WIlsON for analysis of RNA-seq data recently, but encountered problems when uploading the CLARION file. This is the error message that appears:  <html> <head><title>413 Request Entity 
I have been using WIlsON with the same CLARION file before, and a colleague encountered the same error when trying to upload a different dataset, thus I suspect the error might be internal.
For any insight in how to circumvent this problem, I would be grateful, as WIlsON has been of tremendous help so far and I would really like to use it for this analysis!
Best wishes,
Vera

**Comment by hschult** [comment]
Hi Vera,
thank you for showing interest in Wilson! I will gladly help you with this issue but I need some more information.

- How do you run wilson (rstudio, docker, ...)?
- What are your versions? You can see the versions by hovering over the top-left logo in the wilson app.
- Also it would be a great help if you could provide a reduced version of your data. So I can try to reproduce this.

Best wishes
Hendrik

**Comment by veritasnondatur** [comment]
Hi Hendrik,

Thank you very much for your response and offer to help!
I was using the web-application (http://loosolab.mpi-bn.mpg.de/wilson/) of WIlsON. Unfortunately, I do not know which version of WIlsON was running there lately. However, as the website is currently not available, I am assuming you might be working on it right now?  In case you still would like some of the data to reproduce the issue, I am happy to provide it via Email.

Cheerio,
Vera

**Comment by hschult** [comment]
Ah ok, you were using our demo server. No, I didn't do anything yet but thank you for making me aware that it stopped working. I will look into it. And yes please send me your data, that would help immensely with debugging!

Meanwhile, you can try to run WIlsON on your computer.  For that, you need RStudio. Just install the wilson package and run `wilson::install_app()`. This should automatically download and start the app, after which you should be able to use WIlsON as you did before.

**Comment by hschult** [comment]
Hi Vera,

I found that we had an upload limit of 2 mb, which your data exceeded. But this is increased now so you should be able to use the demo server.

I will close this issue, but feel free to reopen if the error persits or open a new issue if you run into other problems.

Cheers
Hendrik
